### ISSUE TITLE
Not Available on Maven

### ISSUE THREAD

**Issue by wright-h** [hunters-ai/spark-adaptive-file-connector#1]
Hello,

From your build code this looks like it should be published to the central maven repository, but I am not able to locate this library on there.

**Comment by woj-i** [comment]
Hello @wright-h !
It's not there yet. We will try to push the artifact to the maven central in a few days. I'll let you know when it will be ready.

**Comment by wright-h** [comment]
My apologies, I thought it was published. Looking forward to the release!

**Comment by woj-i** [comment]
Hi @wright-h !
Now it's available at Maven Central:
```
<dependency>
  <groupId>ai.hunters</groupId>
  <artifactId>spark-adaptive-file-connector_2.12</artifactId>
  <version>1.0.0</version>
</dependency>
```
Please close the issue if it works for you.

**Comment by wright-h** [comment]
Yes, works. Again, apologies for the misunderstanding. Thank you for you work on this!
